GRIDevelopment.UI/Controllers/CustomerController.cs
using System;
using System.Linq;
using GRIDevelopment.BL.Interface;
using GRIDevelopment.Contract.DTO;
using GRIDevelopment.Mpper;
using Microsoft.AspNetCore.Mvc;

namespace GRIDevelopment.UI.Controllers
{
    public class CustomerController : Controller
    {
        
            private readonly ICustomerService _customerService;
            public CustomerController(ICustomerService customerService, DomainCustomerMapper mapper)
            {
                _customerService = customerService;
            }

        public IActionResult Index(string searchString)
        {
            var customers = from p in _customerService.GetAllCustomers() select p;



            if (!String.IsNullOrEmpty(searchString))
            {
                customers = customers.Where(s => s.customer_name!.Contains(searchString));
            }



            else { customers = customers.OrderBy(s => s.customer_name); }
            //_productService.GetAllProducts();
            return View(customers);





        }

        [HttpGet]
        public IActionResult AddEditCustomer(int? id)
        {
            if (id == null)
                return View();
            else
            {
                var supplier = _customerService.GetCustomerById(id.Value);
                return View(supplier);
            }
        }

        [HttpPost]
        public IActionResult AddEditCustomer(CustomerDTO customer)
        {
            if (!ModelState.IsValid)
                return View();

            if (customer.Id > 0)
            {
                _customerService.UpdatePost(customer);
            }
            else
            {
                _customerService.AddCustomer(customer);
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Remove(int id)
        {
            _customerService.RemovePost(id);

            return RedirectToAction("Index");
        }
    }
    
}

GRIDevelopment.UI/Controllers/ProductController.cs
using System;
using System.Linq;
using GRIDevelopment.BL.Interface;
using GRIDevelopment.Contract.DTO;
using GRIDevelopment.Mpper;
using Microsoft.AspNetCore.Mvc;

namespace GRIDevelopment.UI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService, DomainProDTOMapper mapper)
        {
            _productService = productService;
        }

        public IActionResult Index(string searchString)
        {
            var products = from p in _productService.GetAllProducts() select p;



            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(s => s.ProductName!.Contains(searchString));
            }



            else { products = products.OrderBy(s => s.ProductName); }
            //_productService.GetAllProducts();
            return View(products);





        }

        [HttpGet]
        public IActionResult AddEditProduct(int? id)
        {
            if (id == null)
                return View();
            else
            {
                var product = _productService.GetProductById(id.Value);
                return View(product);
            }
        }

        [HttpPost]
        public IActionResult AddEditProduct(ProductDTO product)
        {
            if (!ModelState.IsValid)
                return View();

            if (product.Id > 0)
            {
                _productService.UpdatePost(product);
            }
            else
            {
                _productService.AddProduct(product);
            }

            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Remove(int id)
        {
            _productService.RemovePost(id);

            return RedirectToAction("Index");
        }
        
    }
}

GRIDevelopment.UI/Controllers/SupplierController.cs
using GRIDevelopment.BL;
using GRIDevelopment.BL.Interface;
using GRIDevelopment.Contract.DTO;
using GRIDevelopment.DAL.DomainModel;
using GRIDevelopment.Mpper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace GRIDevelopment.UI.Controllers
{
    public class SupplierController : Controller
    {
        private readonly ISupplierService _supplierService;

        public SupplierController(ISupplierService supplierService, DomainDTOMapper mapper)
        {
            _supplierService = supplierService;
        }

        public IActionResult Index(string searchString)
        {
            //var suppliers = _supplierService.GetAllSuppliers();
            //return View(suppliers);



            var suppliers = from s in _supplierService.GetAllSuppliers() select s;



            if (!String.IsNullOrEmpty(searchString))
            {
                suppliers = suppliers.Where(s => s.SupplierName!.Contains(searchString));
            }



            else { suppliers = suppliers.OrderBy(s => s.SupplierName); }
            //_productService.GetAllProducts();
            return View(suppliers);
        }

        //[HttpGet]
        //public IActionResult AddSupplier()
        //{
        //    return View();
        //}


        //[HttpPost]
        //public IActionResult AddSupplier(SupplierDTO supplier)
        //{
        //    _supplierService.AddSupplier(supplier);

        //    return View();
        //}


        [HttpGet]
        public IActionResult AddEditSupplier(int? id)
        {
            if (id == null)
                return View();
            else
            {
                var supplier = _supplierService.GetSupplierById(id.Value);
                return View(supplier);
            }
        }

        [HttpPost]
        public IActionResult AddEditSupplier(SupplierDTO supplier)
        {
            if (!ModelState.IsValid)
                return View();
            
                if (supplier.Id > 0)
                {
                    _supplierService.UpdatePost(supplier);
                }
                else
                {
                    _supplierService.AddSupplier(supplier);
                }
            
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Remove(int id)
        {
            _supplierService.RemovePost(id);

            return RedirectToAction("Index");
        }

    }
}

GRIDevelopment.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GRIDevelopment.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <link rel="stylesheet" href="~/css/mabootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobstrusive.js"></script>
    <script src="~/lib/bootstrap/js/bootsrap.js"></script>


   



</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            @if (User.Identity.IsAuthenticated)
                    {
                      <div class="container">
                <a class="navbar-brand ml-auto" asp-area="" asp-controller="Home" asp-action="Index">GRI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Supplier" asp-action="AddEditSupplier">Supplier</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="AddEditProduct">Product</a>
                         </li>
                         <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Customer" asp-action="AddEditCustomer">Customer</a>
                        </li>
                    </ul>
                </div>
            </div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                    </li> 
                </ul>
            }

            else
            {
               <div class="container">
                <a class="navbar-brand ml-auto" asp-area="" asp-controller="Home" asp-action="Index">GRI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>

                    
                </div>
            </div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                    </li>
                </ul> 
            }
            
        </nav>
    </header>
    <div class="mainbody">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; All Copyrights Reserved by GRI Tires © 2022 <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/animate-in.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>